/*
 * Copyright DataStax, Inc.
 *
 * Please see the included license file for details.
 */
package com.datastax.bdp.db.tools.nodesync;

/**
 * Generic well-known exception generated by NodeSync command line tool to be displayed whithout stack trace.
 */
public class NodeSyncException extends RuntimeException
{
    NodeSyncException(String message)
    {
        super(message);
    }
}
